version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: medisync
      POSTGRES_PASSWORD: medisync_pass
      POSTGRES_DB: medisync_db
    ports:
      - '5432:5432'
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
  minio:
    image: minio/minio:latest
    command: server /data --console-address ':9001'
    ports:
      - '9000:9000'
      - '9001:9001'